
name: Release
on:
  push:
    tags:
      - test*

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: rwxrob-ghtest1/deploy-with-ssh@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Setup ssh
        run: |
          cat "${{ secrets.SSH_DEPLOYMENT_KEY }}" > ./ssh.priv
          chmod 0600 ./ssh.priv
          mkdir -p ~/.ssh
          cat "${{ secrets.HOST_KEY }}" >> ~/.ssh/known_hosts

      - name: Run ssh command
        run: ssh -i ./ssh.priv "${{secrets.USER}}@${{secrets.HOST}}" time
