
name: Release
on:
  push:
    tags:
      - test*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy to ssh target
    steps:

      - name: Build it
        run: |
          echo "#!/bin/sh" >> hello
          echo "echo hello world" >> hello
          chmod +x hello

      - name: Collect artifacts
        run: |
          mkdir ./deploy
          cp hello ./deploy
          cp README.md ./deploy

      - name: Deploy with ssh/scp
        uses: rwxrob-ghtest1/deploy-with-ssh@v1
        env:
          DIR: ./deploy
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          HOSTKEY: ${{ secrets.HOST_KEY }}
          SSHKEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}

